### PR TITLE
[#21] Fix IllegalAccessError with StageContext

### LINKED ISSUE #21: IllegalAccessError: com/ofg/pipeline/core/PipelineBuilder$StageContext with @CompileStatic
With `@CompileStatic` enabled the following code fails:

```
PipelineBuilder<MyProject> pipelineBuilder = ...

pipelineBuilder.with {
    stage('Build') {
        job BUILD_AND_PUBLISH
    }
    ...
```

with:
```
java.lang.IllegalAccessError: com/ofg/pipeline/core/PipelineBuilder$StageContext

	at com.ofg.pipeline.microservice.template.MicroservicePipelineTemplate.configurePipelineJobs_closure2$_closure5(MicroservicePipelineTemplate.groovy:67)
	at com.ofg.pipeline.core.PipelineBuilder.stage(PipelineBuilder.groovy:27)
	at com.ofg.pipeline.microservice.template.MicroservicePipelineTemplate.configurePipelineJobs_closure2(MicroservicePipelineTemplate.groovy:66)
	at com.ofg.pipeline.microservice.template.MicroservicePipelineTemplate.configurePipelineJobs(MicroservicePipelineTemplate.groovy:64)
	at com.ofg.pipeline.microservice.template.MicroservicePipelineTemplate.configurePipeline_closure1(MicroservicePipelineTemplate.groovy:58)
	at com.ofg.pipeline.core.PipelineBuilder.configure(PipelineBuilder.groovy:21)
	at com.ofg.pipeline.microservice.template.MicroservicePipelineTemplate.configurePipeline(MicroservicePipelineTemplate.groovy:52)
	at com.ofg.pipeline.core.PipelineTemplateBuilder.build(PipelineTemplateBuilder.groovy:30)
	at com.ofg.pipeline.microservice.template.MicroservicePipelineTemplateBuilder.build(MicroservicePipelineTemplateBuilder.groovy:29)
	at com.ofg.pipeline.core.PipelineTemplateBuilder.buildAll_closure1(PipelineTemplateBuilder.groovy:20)
	at groovy.lang.Closure.call(Closure.java:414)
	at groovy.lang.Closure.call(Closure.java:430)
	at com.ofg.pipeline.core.PipelineTemplateBuilder.buildAll(PipelineTemplateBuilder.groovy:19)
	at com.ofg.MicroservicePipelineJobNamesSpec.should create pipeline jobs on default configured instance for backward compatibility(MicroservicePipelineJobNamesSpec.groovy:128)
```

The inner class `StageContext` cannot be private in `PipelineBuilder` as the closure is called on it:
```
void stage(String stageName, @DelegatesTo(StageContext) closure) {
    def stageContext = new StageContext(stageName: stageName)
    stageContext.with(closure)
}
```

### PR DESCRIPTION
**Pull request by szpak**
More details in #21.

Fixed #21.

### CODE REVIEW

File: src/main/groovy/com/ofg/pipeline/core/PipelineBuilder.groovy [hunk 1]
```diff
@@ -27,7 +27,8 @@ class PipelineBuilder<P extends Project> {
         stageContext.with(closure)
     }
 
-    private class StageContext {
+    //Cannot be private as an external closure is called in its context
+    class StageContext {
```
Comment (ArturGajowy) [inline src/main/groovy/com/ofg/pipeline/core/PipelineBuilder.groovy:31]: a test reproducing the issue would be handy ;)

Comment (szpak) [reply src/main/groovy/com/ofg/pipeline/core/PipelineBuilder.groovy:31]: Good idea. I've tried it in the morning, but it doesn't want to fail when code is in jenkins-pipeline-dsl project itself. The same test case fails when run against the same codebase, however, packaged as a jar... I will try to return to that later.
